### ISSUE TITLE
rank history

### ISSUE THREAD

**Issue by Maxluli** [ppy/osu-api#293] opened 2020-01-24 09:34 UTC
i did search on the wiki page and in all the issues and i did'nt find any talking about getting the rank history of a player to make a graph like on the osu website.

**Comment by Maxluli** [comment] 2020-01-24 09:36
sorry there is documentation for get_user_best my bad, but for the images and other function there is a lack of documentation is it normal?

**Comment by Liam-DeVoe** [comment] 2020-01-24 11:48
duplicate of #215 ?

**Comment by peppy** [comment] 2020-01-26 08:31
Should probably be requested against [ppy/osu-web](https://github.com/ppy/osu-web) instead (in the new api version).

**Closed as completed by peppy** 2020-01-26 08:31 UTC
