### ISSUE TITLE
Missing expanded difficulty data

### ISSUE THREAD

**Issue by stochasticwalk** [ppy/osu-api#252] opened 2019-05-14 07:23 UTC
This map https://osu.ppy.sh/beatmapsets/144171#osu/378344 doesn't return the new aim, speed, and strain difficulties added to /get_beatmaps

**Comment by Magnus-Cosmos** [comment] 2019-05-14 21:28
Noticed a similar problem, this entire beatmapset https://osu.ppy.sh/s/106443 has null for diff_strain

Also, on the beatmap you linked, a large amount of scores on the leaderboard return null pp values

**Comment by GrilledCheeese** [comment] 2019-05-17 13:21
This map has None/null values for difficultyrating and diff_speed:
https://osu.ppy.sh/beatmapsets/937970#fruits/1962371
When using /get_beatmaps

**Comment by GrilledCheeese** [comment] 2019-05-17 15:47
This LOVED beatmap gives None value for pp instead of 0:
https://osu.ppy.sh/beatmapsets/375956#osu/823257
When using /get_scores

**Comment by doughn0** [comment] 2019-05-19 00:25
I have noticed that a lot of map_data(`max_combo`, `diff_aim`, `diff_speed`, `difficultyrating`) becomes null when requested with mods that don't change the difficulty, like HD or SD. This happened for me even on ranked maps. [Look at this for example.](https://media.discordapp.net/attachments/335004443609137152/579451818115858452/unknown.png)

**Comment by Magnus-Cosmos** [comment] 2019-05-19 05:04
Yeah, I tested mods as well and the only mods that work are HR, EZ, DT, and HT (and obviously combining HR with EZ or DT with HT will result in null values)

My suggestion for this would be to make it so that all the other mods should have no effect on the values rather than making the values null

**Comment by ThePooN** [comment] 2019-05-19 13:56
@doughn0's issue is different and was already addressed by peppy here: https://github.com/ppy/osu-api/issues/126#issuecomment-489489817
You can refer to how I handled this issue here: https://github.com/ThePooN/nodesu/blob/6ce855ad1733df5042a3c430c3bd7afefef3f9a2/lib/components/BeatmapsComponent.js#L29

**Comment by doughn0** [comment] 2019-05-19 15:12
Oh I see, thanks.

**Comment by peppy** [comment] 2019-06-04 07:40
Closing as intended behaviour (maybe update the wiki documentation mentioning this?)

**Closed as completed by peppy** 2019-06-04 07:40 UTC
