### ISSUE TITLE
add user_join date to /get_user response

### ISSUE THREAD

**Issue by Liam-DeVoe** [ppy/osu-api#228] opened 2018-10-26 17:52 UTC
Use case would be to add it to the r/osureport bot (https://reddit.com/u/OsuReportBot) comment response, for blatant multis.

Also suggested in #170 and #150.

**Comment by peppy** [comment] 2018-10-30 19:52
Please don't open new issues if they already exist. You can post a reply instead.

Duplicate of #150.

**Closed as completed by peppy** 2018-10-30 19:52 UTC
