### ISSUE TITLE
beatmap downloads truncated to 1MB?

### ISSUE THREAD

**Issue by Tillerino** [ppy/osu-api#131] opened 2016-06-05 10:41 UTC
Well this is technically not an "API" issue, but I guess this place is as good as any to post about this.

It looks like beatmap files are truncated when downloaded via the website, e.g. `https://osu.ppy.sh/osu/777867`. This download is truncated to _exactly_ 1MB, so it's probably no coincidence.

There are a couple of more beatmaps where this occurrs:

```
893209
621903
621905
621907
871542
777875
616659
```

**Comment by peppy** [comment] 2016-06-05 10:42
Honestly not sure we should be ever promoting .osu files over 1mb as being a usable thing...

**Comment by omkelderman** [comment] 2016-06-05 12:33
b-b-but... awesome storyboards?

**Comment by hypereddie** [comment] 2016-06-08 20:05
> Honestly not sure we should be ever promoting .osu files over 1mb as being a usable thing...
The maps shouldn't be accepted then. Accepting the maps and truncating them seems weird IMO...

**Comment by Tillerino** [comment] 2017-06-17 09:26
@peppy Any updates? Been a year...

**Comment by peppy** [comment] 2017-06-18 09:53
I just looked into this today. The issue is quite deeply ingrained in BSS. I've added a todo for fixing it and estimate it will be complete this week.

tl;dr the server-side files are actually truncated and need to be repaired.

**Comment by Syriiin** [comment] 2019-11-25 06:16
Looks like it's been fixed recently. Time to close this ancient issue?

**Comment by peppy** [comment] 2019-11-25 06:26
Yep, has since been fixed, and I believe we've retroactively fixed all the broken files.

**Closed by peppy** 2019-11-25 06:26 UTC
